### ISSUE TITLE
[BUG] 'SUI' tried to call the protected function 'UseAction()'.

### ISSUE THREAD

**Issue by Syzuna** [Syiana/SUI#100]
**Describe the bug**
In random intervals I seem to run into an issue that causes my keybind input to be blocked.
The game states SUI tried to use a blocked action in that case and I have to reload to get rid of it.

**To Reproduce**
I literally don't know how to reproduce this.
It seems to be completely random, sometimes after I start a key, sometimes I just used a portel.

**Bugsack Stacktrace**
```
1x [ADDON_ACTION_FORBIDDEN] AddOn 'SUI' tried to call the protected function 'UseAction()'.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `UseAction'
[string "@FrameXML/SecureTemplates.lua"]:364: in function `handler'
[string "@FrameXML/SecureTemplates.lua"]:690: in function <FrameXML/SecureTemplates.lua:672>
[string "@FrameXML/SecureTemplates.lua"]:704: in function <FrameXML/SecureTemplates.lua:697>
[string "@FrameXML/SecureTemplates.lua"]:746: in function `SecureActionButton_OnClick'
[string "@FrameXML/ActionButton.lua"]:93: in function `TryUseActionButton'
[string "@FrameXML/ActionButton.lua"]:128: in function `ActionButtonDown'
[string "ACTIONBUTTON2"]:2: in function <[string "ACTIONBUTTON2"]:1>

Locals:
_ = Frame {
 RegisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:486
 0 = <userdata>
 UnregisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:486
 SetScript = <function> defined @!BugGrabber/BugGrabber.lua:486
}
event = "ADDON_ACTION_FORBIDDEN"
events = <table> {
 ADDON_ACTION_BLOCKED = <function> defined @!BugGrabber/BugGrabber.lua:552
 ADDON_ACTION_FORBIDDEN = <function> defined @!BugGrabber/BugGrabber.lua:552
 PLAYER_LOGIN = <function> defined @!BugGrabber/BugGrabber.lua:546
 LUA_WARNING = <function> defined @!BugGrabber/BugGrabber.lua:561
 ADDON_LOADED = <function> defined @!BugGrabber/BugGrabber.lua:506
 ```

**Which World of Warcraft version (please complete the following information):**
 - Retail

**Comment by muleyo** [comment]
Hey,

could you please do the following steps?

- Please enter the following command into your chat: `/console taintLog 1`
- After you run into "Action blocked by SUI" by pressing action buttons, please upload the taint.log file which can be found in your WoW folder (`...\World of Warcraft\_retail_\Logs\`)

**Comment by Syzuna** [comment]
Will do.
Like I said it is really hard to reproduce...
E.g. I didnt get it a single time yesterday but 2 times the day before while doing the same things.
So I dont know when I will be able to get you some more data

**Comment by muleyo** [comment]
I just updated SUI and fixed 1 taint error which COULD potentially lead to this issue. Please get the latest version and do the steps regardless. Make sure to enable taintLog every time you start WoW and whenever you run into this issue, report back.

**Comment by Syzuna** [comment]
Will do thanks!
