### ISSUE TITLE
Dungeon Finder Eye ball icon missing [BUG]

### ISSUE THREAD

**Issue by Stringthumper** [Syiana/SUI#102]
**Describe the bug**
Since the 10.1 patch, I've been unable to find my dungeon finder icon (the eyeball), when I disable SUI, its back right beside the menu options. Unsure if this is due to that patch, or if I somehow disabled the eyeball icon 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Which World of Warcraft version (please complete the following information):**
Retail

**Additional context**

**Comment by muleyo** [comment]
You can move the Queue Eye in EditMode. It should be somewhere around your minimap.

**Comment by Stringthumper** [comment]
It's nowhere to be found in edit mode, it was there day 1 of 10.1, but it's no longer there when I have SUI enabled, but it's there when SUI is disabled
________________________________

**Comment by pjbanko** [comment]
i have the same btw! i have it on minimap and its randomly disappearing! if i hold my mouse on the position, where it should be, its showing me im still in que in tooltip, so its only visually gone. if i reload, its back again. but kinda annoying, agree!

**Comment by muleyo** [comment]
Are you using the latest version? I've fixed that issue a few versions earlier.

@Stringthumper it should be there for sure, for me it's next to my minimap.

![image](https://github.com/Syiana/SUI/assets/32986026/55d3410e-f40e-4569-9339-9bc756bba7e3)

**Comment by pjbanko** [comment]
Yes ofc, using curseforge daily!

muleyo ***@***.***> schrieb am Di. 9. Mai 2023 um 22:46:

**Comment by Stringthumper** [comment]
Yep, update daily
________________________________

**Comment by muleyo** [comment]
Please try to reset your SUI settings. You're the only 2 people who are reporting about this atm. I personally don't have that issue at all.

Don't forget to report back afterwards. Thanks!

**Comment by pjbanko** [comment]
I will tomorrow and let u know!

muleyo ***@***.***> schrieb am Di. 9. Mai 2023 um 23:53:

**Comment by Stringthumper** [comment]
I did the SUI reset and it worked. Thanks much, didn't even know there was a reset setting. Sorry for making a nonexistent issue lol.
________________________________

**Comment by pjbanko** [comment]
Where is it? Haha

Stringthumper ***@***.***> schrieb am Mi. 10. Mai 2023 um
02:42:

**Comment by Stringthumper** [comment]
The reset - under the faq section
The eye all - was by the minimal when I turned on edit mode
________________________________
