### ISSUE TITLE
[BUG] Raid Party Frame Custom Size

### ISSUE THREAD

**Issue by pjbanko** [Syiana/SUI#103]
**Describe the bug**
YOYO,

I have my Party Frames on Custom to make them bigger and see my Teammates Health better. I track my Teammates DRS and CDS with the Party Frames aswell. Only because of your SUI i could make them bigger and super clear to see.

Since 10.1 its not working as before. I join into a arena, and my Partyframes are Default and not Custom sized anymore, like i havent SUI installed and using default Party Frames. If i reload, it shows my party frames in normal custim size i set up in SUI. Perfect :-) but then the match starts and mid game it turns small and into default size again. 

The bug is, that the cumstom setup Party frames are randomly turning into default midfight or in the start of a arena match. very annoying and i hope u guys are able to fix that, thanks <3 i put in 2 screenshots to make the difference clear. the bigger party frames are how i set them up in custom, the small party frames are appearing midfight or before reload.

![WoWScrnShot_050923_004857](https://user-images.githubusercontent.com/132960315/236962636-fe2fe0d7-6a06-42c5-8601-9d7eee6d81ac.jpg)
![WoWScrnShot_050923_004903](https://user-images.githubusercontent.com/132960315/236962649-5f582932-810a-4f6d-af42-ba3bae573936.jpg)

**Comment by muleyo** [comment]
Please try my AddOn: Party Raidframe Resize and tell me if it works.

**Comment by pjbanko** [comment]
its working!!

Am Di., 9. Mai 2023 um 11:44 Uhr schrieb muleyo ***@***.***>:

**Comment by pjbanko** [comment]
i hope its keeping the size consitant haha! ty for your work :-)

**Comment by muleyo** [comment]
Glad it's working, gotta update SUI soon :)
