### ISSUE TITLE
[BUG] Queue Status Button not showing

### ISSUE THREAD

**Issue by dev-wagner-zoccoli** [Syiana/SUI#108]
**Describe the bug**
When SUI is enabled, the micromenu bugs out in edit mode, messing up it's width and positioning. For the positioning, it corrects itself by leaving edit mode. But the queue status button disappears. Made tests disabling addon by addon and it happens only with SUI (even when only by itself). Also tested it with the option "show" enabled in the options menu for the micromenu. Also tried using addons only for moving the queue frame with no success.

**To Reproduce**
1. Try the LFG tool...
2. look for the Queue Status Button
3. Nowhere to be found...
4. Appears when SUI is disabled

**Expected behavior**
Queue Status Button should appears when in queue (was working fine couple days agon).

**Screenshots**
(https://drive.google.com/drive/folders/1I5xkxxrJuZAMmT1X6ZcMfa1UG_08GgF5?usp=sharing)

**Which World of Warcraft version (please complete the following information):**
 Retail - Dragonflight

**Additional context**
DNA

**Comment by muleyo** [comment]
Please delete all settings through the Curse Client or in your WTF folder:

`World of Warcraft\_retail_\WTF\Account\YourAccount\SavedVariables\SUI.lua`
`World of Warcraft\_retail_\WTF\Account\YourAccount\SavedVariables\SUI.lua.bak`

**Comment by dev-wagner-zoccoli** [comment]
TY! That did the trick! And thanks to all of you who work on this addon. Can't leave without it anymore! Cheers!
