### ISSUE TITLE
No Difference between purgeable buffs and not purgeable

### ISSUE THREAD

**Issue by pjbanko** [Syiana/SUI#109]
**Describe the bug**
i target someone and in default ui, there is a white border around buffs, i can purge off/dispell off. i added a screenshot to show, that there is no difference.

i made a red border around the area. like u see, the powerword fortitude (which is purgeable) has no white border around it. any idea how i change this?

![WoWScrnShot_070123_024738](https://github.com/Syiana/SUI/assets/132960315/27afa058-5ae9-41ec-8026-baf6aeb7bd55)

thanks a lot!

**Comment by muleyo** [comment]
With that brightness, I can't see anything. However, for me it's working just fine..
