### ISSUE TITLE
No calender[BUG]

### ISSUE THREAD

**Issue by Ahllbrn** [Syiana/SUI#113]
**Describe the bug**
It seems to be that with SUI enabled the button to open the calendar is missing
**To Reproduce**
1. Go to 'enable SUI'
2. Click on 'nothing, the button is missing xD'

**Comment by muleyo** [comment]
![image](https://github.com/Syiana/SUI/assets/32986026/be90116c-62dc-4348-9c55-326a76d170d8)

I don't see any issues here? You can simply enable it in SUI.

**Comment by Ahllbrn** [comment]
Ugh, I feel so stupid. Thank you very much for taking the time to show this
to me. Keep up the great work, ive always loved your UI
