### ISSUE TITLE
[SUGGESTION] Buff / Debuff size and number of auras shown in unit frames

### ISSUE THREAD

**Issue by fekz** [Syiana/SUI#116]
Hello, I'd like to suggest a couple of features to further improve this amazing addon.

1 - Add size configuration for auras in Unit Frames
2 - Add configuration for number of auras shown in Unit Frames

Thanks!

**Comment by muleyo** [comment]
Size can be configured already.
For numbers: Get OmniCC, gives you full freedom of all Cooldown, Buff and Debuff timers.

![image](https://github.com/Syiana/SUI/assets/32986026/854a173d-927e-40ad-afe9-f3bffd1fb5c8)

**Comment by muleyo** [comment]
Misunderstood your 2nd suggestion. Won't happen, limiting the amount buffs/debuffs you can see is not really a good thing.
