### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by lordgravy** [Syiana/SUI#117]
Cannot seem to enable Target of Target.  I have it enabled in the system interface options and it shows up if I turn off SUI, but I don't see options for it in SUI or see it when I load SUI. 

**To Reproduce**
Enable Target of Target in system settings. 

**Expected behavior**
No Target of Target Frame is active in SUI

**Screenshots**

**Which World of Warcraft version (please complete the following information):**
 - Wotlk

**Additional context**

**Comment by muleyo** [comment]
WOTLK is not supported by us, it's a community project nowadays.
