### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by chernyshovvo** [Syiana/SUI#118]
**Describe the bug**

the SUI not works. As you see on screenshot, all menus is empty 

**Expected behavior**

i wish it works 

**Screenshots**

**Which World of Warcraft version (please complete the following information):**
 - Retail 10.1.5.50747 Dragonflight
  

**Additional context**
Add any other context about the probl
![234](https://github.com/Syiana/SUI/assets/126977796/4d3be633-565e-4e85-af02-d06c9d7ffb27)
![123](https://github.com/Syiana/SUI/assets/126977796/abe5145e-db5f-492b-a739-d439fd458207)

**Comment by muleyo** [comment]
Reset your SUI settings (FAQ => Reset)
