### ISSUE TITLE
Interface custom color bugged since update [BUG]

### ISSUE THREAD

**Issue by An4korn** [Syiana/SUI#119]
**Describe the bug**
Interface custom color bugged since update. Just one bind is colored

**Screenshots**
[If applicable, add screenshots to help explain your problem.] https://i.imgur.com/se69o0T.png https://i.imgur.com/q7J6omo.png

**Which World of Warcraft version (please complete the following information):**
 - Retail

**Comment by Daddybaldcool** [comment]
I also have the same problem as showed in the screenshot provided by Ank4horn.

**Comment by muleyo** [comment]
Issue has been fixed with today's update.
