### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Rokonen** [Syiana/SUI#123]
Installed on Classic HC and it renders the game unplayable. My mouse doesn't work (can't click anything) and the "Welcome to SUI" message is stuck on the screen. I also can't hit enter in the chat window so typing /SUI doesn't work. Basically all I can do is press escape and logout. It does appear to be reskinning the UI at least. I disabled all of my other add-ons and still have the problem.

**Comment by Wisp404** [comment]
Hello,  i found a fix, delete install in Addons/SUI/Config

**Comment by PhilFrag** [comment]
Hi, this actually worked and the addon seems to be running as intended. Unfortunately, there is no way to customize it.
