### ISSUE TITLE
[BUG] Very common blocked actions (taint)

### ISSUE THREAD

**Issue by ehargarther** [Syiana/SUI#128]
**Describe the bug**
Since 10.1.7 taint errors are displayed at random very frequently.

**To Reproduce**
This can happen at any time with no action taken

**Expected behavior**
No errors

**Screenshots**
![image](https://github.com/Syiana/SUI/assets/105167521/88d872f2-4c6f-4764-972d-153322d63421)

**Which World of Warcraft version (please complete the following information):**
 - Retail, 10.1.7

**Additional context**

**Comment by muleyo** [comment]
Not much I can do about it. I've reworked the whole actionbar styling code already, I still don't know what's causing this... this is since DF start.
