### ISSUE TITLE
Better discord admins please

### ISSUE THREAD

**Issue by Mahavailo89** [Syiana/SUI#132]
Recently I had issues with one of your discord admins. After she failed to help, and was unable to provide answer she banned me from discord. You should definitely look who and how people are managing requests for help. If I was rude or disrespectful in any shape of from I would understand, but this is seriously unprofessional

**Comment by muleyo** [comment]
Hello,

what's your Discord username? I'd like to track the messages down, but I cannot find anything.

**Comment by Mahavailo89** [comment]
My discord name is Aj_maha_vailo

**Comment by muleyo** [comment]
You've been banned on January 30th. That's almost 10 months ago. May I ask why you complain about it that late?

**Comment by Mahavailo89** [comment]
Didn't know it was so long. LoL .. Well honestly I decided to give SUI shot again since I miss the dark frames honestly. And I have the same issues. I always used SUI and AnyFont in combination. Now I can't anymore. AnyFont was used to change floating combat text

**Comment by muleyo** [comment]
Well, we're not gonna change something just because another Add-on is not working along with SUI. That's just unfortunate. And honestly, Floating Combat Text is completely irrelevant. You already get all information from Details.

**Comment by Mahavailo89** [comment]
That’s fine. I was just asking back then and even now is there any way to change it that you guys know. Thnx for the response. At least this response is not rude like last one it was that literally banned me from server for not knowing answer to my question

**Comment by muleyo** [comment]
Gonna close here for now. I've unbanned you on the Discord. Maybe you'll use SUI again at some point. Best of luck in your WoW adventures!
