### ISSUE TITLE
Error  Ui Patch 10.2

### ISSUE THREAD

**Issue by NoRRt** [Syiana/SUI#133]
Message: bad argument #2 to '?' (outside of expected range 0 to 4294967295 - Usage: local result = UnitIsPlayer([unit, partyIndex]))
Time: Wed Nov  8 19:58:55 2023
Count: 5
Stack: bad argument #2 to '?' (outside of expected range 0 to 4294967295 - Usage: local result = UnitIsPlayer([unit, partyIndex]))
[string "=[C]"]: ?
[string "=[C]"]: in function `UnitIsPlayer'
[string "@Interface/AddOns/SUI/Modules/Tooltip/_Core.lua"]:56: in function <Interface/AddOns/SUI/Modules/Tooltip/_Core.lua:53>
[string "@Interface/AddOns/SUI/Modules/Tooltip/_Core.lua"]:155: in function <Interface/AddOns/SUI/Modules/Tooltip/_Core.lua:66>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `securecallfunction'
[string "@Interface/SharedXML/Tooltip/TooltipDataHandler.lua"]:162: in function <Interface/SharedXML/Tooltip/TooltipDataHandler.lua:157>
[string "@Interface/SharedXML/Tooltip/TooltipDataHandler.lua"]:182: in function <Interface/SharedXML/Tooltip/TooltipDataHandler.lua:178>
[string "@Interface/SharedXML/Tooltip/TooltipDataHandler.lua"]:218: in function <Interface/SharedXML/Tooltip/TooltipDataHandler.lua:208>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface/SharedXML/Tooltip/TooltipDataHandler.lua"]:243: in function <Interface/SharedXML/Tooltip/TooltipDataHandler.lua:236>
[string "@Interface/SharedXML/Tooltip/TooltipDataHandler.lua"]:389: in function <Interface/SharedXML/Tooltip/TooltipDataHandler.lua:339>
[string "=[C]"]: in function `securecallfunction'
[string "@Interface/SharedXML/Tooltip/TooltipDataHandler.lua"]:336: in function `ProcessInfo'
[string "@Interface/FrameXML/GameTooltip.lua"]:1092: in function `SetWorldCursor'
[string "@Interface/FrameXML/UIParent.lua"]:1484: in function <Interface/FrameXML/UIParent.lua:1407>

Locals: (*temporary) = <function> defined =[C]:-1

**Comment by muleyo** [comment]
Fixed in the latest update :) thanks for the report
