### ISSUE TITLE
Unit frames not staying in saved position (Classic Hardcore)

### ISSUE THREAD

**Issue by BrockSparks** [Syiana/SUI#136]
Version: classic hardcore. Whenever I adjust my unit frames and save they reset. If I adjust them and don't save they stay until I log off then reset upon login.

**Comment by muleyo** [comment]
If you moved them with Leatrix Plus or something similar, this might be the issue.

**Comment by BrockSparks** [comment]
> If you moved them with Leatrix Plus or something similar, this might be the issue.

Hmmm okay I'll take a look

**Comment by BrockSparks** [comment]
> If you moved them with Leatrix Plus or something similar, this might be the issue.

That was it, I figure it may have been another add on. Thanks

**Comment by BrockSparks** [comment]
Leatrix plus was fighting with sui. Issue resolved
