### ISSUE TITLE
[BUG] does not honor the leatrix plus buff frame placement like it does for the unit frame placement

### ISSUE THREAD

**Issue by chadhs** [Syiana/SUI#138]
**Describe the bug**
The buff section gets put back in the default minimap location when SUI is enabled.

**To Reproduce**
1. Move the buffs frame to a new location with Leatrix Plus
2. Enable SUI
3. Buffs will display in the default minimap location

**Expected behavior**
Buffs will display where they were placed by Leatrix Plus, in the same way Unit Frames stay put.

**Which World of Warcraft version (please complete the following information):**
 - Vanilla / Era

**Additional context**
This may be a feature request to support this.  Or perhaps another solution is to add a feature to allow moving the buff/debuff location using SUI.

**Comment by muleyo** [comment]
Don't use SUI and Leatrix together or at least disable the Unitframe options in the Leatrix options.
