### ISSUE TITLE
[SUGGESTION] Some QoL options

### ISSUE THREAD

**Issue by u8Jj3** [Syiana/SUI#139]
Hello,

Here is some options that I miss and I think these small addtions would be great for SUI.

- Unitframes
  - Hide Corner Icon
  - Hide Level (At max level ?)

- Map
  - Minimap
    - Dragon Isles Summary icon
      - Option to hide it
      - Make it mouseover when "Buttons on Mouseover" is active
      - Skin it when using Dark Theme

- Misc
  - Hide SUI in the 'esc' menu

Thank you very much :)

**Comment by muleyo** [comment]
Hi,

I've added your suggestions to SUI.

Regarding the Expansion Minimap Button: Styling on this button doesn't work, so it hasn't been added. Also I didn't add an option to hide it, I think Mouseover is more than enough.
