### ISSUE TITLE
[BUG] Flashing status glow on Big player frame incorrect size

### ISSUE THREAD

**Issue by adamschachne** [Syiana/SUI#140]
**To Reproduce**
1. Go to Unit Frames
2. Enable `Big` Style and `Status Glow`
3. Right click an enemy unit

**Expected behavior**
The whole health bar should glow, not the portion of it as if it were the normal variant

**Screenshots**
![image](https://github.com/Syiana/SUI/assets/13020251/feb18e4f-23de-471c-a3b0-becef2a1c212)
![image](https://github.com/Syiana/SUI/assets/13020251/cf166509-12e1-4f61-b33f-d4efc8c54877)

**Which World of Warcraft version (please complete the following information):**
 - Wotlk
 - Vanilla
other game versions not tested

**Comment by muleyo** [comment]
We don't support any other version than Retail.

All the classic versions are a community project nowadays.
