### ISSUE TITLE
LUA error whenever I target any character [BUG]

### ISSUE THREAD

**Issue by ChillyBboy** [Syiana/SUI#141]
**Describe the bug**
Getting a LUA error everytime i target any player, NPC or mob. I diabled all other addons and still get this error

**To Reproduce**
Target any character 

**Which World of Warcraft version (please complete the following information):**
 - Vanilla SOD

**Additional context**
34x SUI/Modules/UnitFrames/_Target.lua:12: attempt to index field 'LeftText' (a nil value)
[string "@SUI/Modules/UnitFrames/_Target.lua"]:12: in function <SUI/Modules/UnitFrames/_Target.lua:10>
[string "=[C]"]: ?
[string "=[C]"]: in function `TargetFrame_CheckClassification'
[string "@Interface_Vanilla/FrameXML/TargetFrame.lua"]:130: in function `TargetFrame_Update'
[string "@Interface_Vanilla/FrameXML/TargetFrame.lua"]:162: in function <Interface_Vanilla/FrameXML/TargetFrame.lua:154>
[string "=[C]"]: in function `CameraOrSelectOrMoveStop'
[string "CAMERAORSELECTORMOVE"]:4: in function <[string "CAMERAORSELECTORMOVE"]:1>

Locals:
self = TargetFrame {
 0 = <userdata>
 debuffs = TargetFrameDebuffs {
 }
 portrait = TargetFramePortrait {
 }
 totFrame = TargetFrameToT {
 }
 raidTargetIcon = TargetFrameTextureFrameRaidTargetIcon {
 }
 highLevelTexture = TargetFrameTextureFrameHighLevelTexture {
 }
 DragFrame = Frame {
 }
 petBattleIcon = TargetFrameTextureFramePetBattleIcon {
 }
 prestigePortrait = TargetFrameTextureFramePrestigePortrait {
 }
 showAuraCount = true
 showLeader = true
 healthbar = TargetFrameHealthBar {
 }
 pvpIcon = TargetFrameTextureFramePVPIcon {
 }
 buffsOnTop = false
 questIcon = TargetFrameTextureFrameQuestIcon {
 }
 deadText = TargetFrameTextureFrameDeadText {
 }
 noTextPrefix = true
 buffs = TargetFrameBuffs {
 }
 nameBackground = TargetFrameNameBackground {
 }
 showLevel = true
 levelText = TargetFrameTextureFrameLevelText {
 }
 leaderIcon = TargetFrameTextureFrameLeaderIcon {
 }
 statusSign = -1
 unit = "target"
 showPVP = true
 borderTexture = TargetFrameTextureFrameTexture {
 }
 showPortrait = true
 TOT_AURA_ROW_WIDTH = 101
 auraRows = 0
 statusCounter = 0
 unconsciousText = TargetFrameTextureFrameUnconsciousText {
 }
 spellbar = TargetFrameSpellBar {
 }
 manabar = TargetFrameManaBar {
 }
 unitHPPercent = 1
 prestigeBadge = TargetFrameTextureFramePrestigeBadge {
 }
 showClassification = true
 menu = <function> defined @Interface_Vanilla/FrameXML/TargetFrame.lua:95
 textureFrame = TargetFrameTextureFrame {
 }
 name = TargetFrameTextureFrameName {
 }
 Background = TargetFrameBackground {
 }
}
forceNormalTexture = nil
fontSize = 11
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'LeftText' (a nil value)"
db = <table> {
 texture = "Interface\AddOns\SUI\Media\Textures\Status\Smooth"
 unitframes = <table> {
 }
}

**Comment by muleyo** [comment]
Get ModernTargetFrame, this will solve the issue since you are using "Big" unitframes.
