### ISSUE TITLE
[BUG] wotlk - Totem Bar moving while in combat behind actionbars

### ISSUE THREAD

**Issue by Vilatsa** [Syiana/SUI#142]
Totem Bar moving while in combat behind action bars

Enter combat
Click keybinds for actionbar spells
watch totem bar move behind actionbar

**Expected behavior**
Expect Totem Bar not to move

**Screenshots**
![image](https://github.com/Syiana/SUI/assets/58783965/443a5362-3168-4636-991a-1d4286aa2015)
The Totem Bar is behind the top left action bar

**Which World of Warcraft version (please complete the following information):**
 - Wotlk

**Additional context**
[See attached video of bug happening in action.](https://streamable.com/i5aubg)

Also tested with all addons disabled besides SUI, behavior still happens with only SUI enabled

**Comment by muleyo** [comment]
Classic versions are not supported anymore.
