### ISSUE TITLE
[BUG]SUI- Retail- tooltip mousing over spells show no info. it only shows an ID number.

### ISSUE THREAD

**Issue by Wynter77** [Syiana/SUI#143]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Which World of Warcraft version (please complete the following information):**
 - Retail
 - Wotlk
 - Tbc
 - Vanilla

**Additional context**

**Comment by muleyo** [comment]
Not an SUI issue. Enable enhanced spell tooltip information by CVar.

```/console UberTooltips 1```
