### ISSUE TITLE
[BUG] Error Friendslist

### ISSUE THREAD

**Issue by Slygon87** [Syiana/SUI#144]
*Message: Interface/AddOns/SUI/Modules/Chat/_Friendlist.lua:181: attempt to index local 'classc' (a nil value)
Time: Thu Jan  4 11:32:40 2024
Count: 1
Stack: Interface/AddOns/SUI/Modules/Chat/_Friendlist.lua:181: attempt to index local 'classc' (a nil value)
[string "@Interface/FrameXML/FriendsFrame_Shared.lua"]:1116: in function `FriendsFrame_CheckBattlenetStatus'
[string "@Interface_Vanilla/FrameXML/FriendsFrame_Vanilla.lua"]:121: in function `FriendsFrame_OnEvent'
[string "*FriendsFrame.xml:3817_OnEvent"]:1: in function <[string "*FriendsFrame.xml:3817_OnEvent"]:1>

Locals: frame = FriendsFrameBattlenetFrame {
 0 = <userdata>
 UnavailableInfoFrame = Frame {
 }
 BroadcastButton = Button {
 }
 BroadcastFrame = Frame {
 }
 UnavailableInfoButton = Button {
 }
 UnavailableLabel = FontString {
 }
 Tag = FontString {
 }
}
playerRealmID = 5832
playerRealmName = "Chaos Bolt"
playerFactionGroup = "Horde"

what could i do?

**Comment by muleyo** [comment]
Classic is not supported anymore.
