### ISSUE TITLE
[BUG] Rune of the Fallen Crusader trails off screen

### ISSUE THREAD

**Issue by michael-farwell** [Syiana/SUI#145]
**Describe the bug**
Rune of the Fallen Crusader trails off  screen

**Expected behavior**
Longer named enchants should be shortened to fit in character screen.

**Screenshots**
![Screenshot 2024-01-20 082131](https://github.com/Syiana/SUI/assets/21293442/1f3d4602-f746-4de4-9bd1-18c4386e8672)

**Which World of Warcraft version (please complete the following information):**
 - Retail

**Additional context**

**Comment by muleyo** [comment]
Hey, I'll fix it soon. Thanks for reporting.

**Comment by muleyo** [comment]
Should be resolved with the latest update.
