### ISSUE TITLE
[BUG] Quest Log Display Issue

### ISSUE THREAD

**Issue by KevSteele** [Syiana/SUI#146]
**Describe the bug**
Quest log is misaligned and out of whack

**To Reproduce**
1. log into a character
2. press 'L' to open quest log
3. behold the horror
4. this doesn't happen if I switch to blizzard theme

**Expected behavior**
Quest log to load appropriately

**Screenshots**

![qlog](https://github.com/Syiana/SUI/assets/5953727/8f903249-b855-4d4f-b02f-f01c295b8dc3)

**Which World of Warcraft version (please complete the following information):**
 - Vanilla

**Additional context**
I tried disabling all other addons and the problem persists with just SUI loaded.

**Comment by muleyo** [comment]
Not supported anymore.
