### ISSUE TITLE
[BUG] Dungeon Browser ICON

### ISSUE THREAD

**Issue by Yushi91** [Syiana/SUI#148]
**Describe the bug**
The Bug is that the Dungeon/raid browser are not on the screen anymore.

**To Reproduce**
1. Go to the Dungeon Browser 
2. Click on finding a group
3. See error 

**Expected behavior**
I want to see how much ppl left to start the raid/dungeon or if its even still up there and i didn't notice it while i was gone for a short period of time from my pc.

**Screenshots**

**Which World of Warcraft version (please complete the following information):**
 - Retail
 

**Additional context**
I did add a Picture of the problem.
![SUI BUGF](https://github.com/Syiana/SUI/assets/91940928/3d7d1cf2-7c4b-437a-806f-692e1361317c)

**Comment by Yushi91** [comment]
With the SUI on i cant see the icon if i turn the addon off the icon is there.

**Comment by muleyo** [comment]
Reset your SUI settings, then it should work properly again.
