### ISSUE TITLE
[BUG] LUA Error

### ISSUE THREAD

**Issue by BlackandYoung** [Syiana/SUI#149]
Message: Interface/AddOns/SUI/Modules/General/_Itemlevel.lua:323: attempt to index field '?' (a nil value)
Time: Tue Feb 13 19:22:33 2024
Count: 97
Stack: Interface/AddOns/SUI/Modules/General/_Itemlevel.lua:323: attempt to index field '?' (a nil value)
[string "@Interface/AddOns/SUI/Modules/General/_Itemlevel.lua"]:323: in function <Interface/AddOns/SUI/Modules/General/_Itemlevel.lua:264>
[string "@Interface/AddOns/SUI/Modules/General/_Itemlevel.lua"]:383: in function <Interface/AddOns/SUI/Modules/General/_Itemlevel.lua:383>

Locals: button = CharacterSecondaryHandSlot {
 0 = <userdata>
 SetItemButtonTexture = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:674
 SetItem = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:544
 IconOverlay = Texture {
 }
 SetAlpha = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:631
 checkRelic = false
 showMatchHighlight = true
 icon = CharacterSecondaryHandSlotIconTexture {
 }
 ignoreTexture = Texture {
 }
 UpdateAzeriteRank = <function> defined @Interface/FrameXML/AzeritePaperDollItemOverlay.lua:46
 UpdateTooltip = <function> defined @Interface/FrameXML/PaperDollFrame.lua:1762
 GetBagID = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:643
 ResetAzeriteTextures = <function> defined @Interface/FrameXML/AzeritePaperDollItemOverlay.lua:75
 RankFrame = Frame {
 }
 count = 0
 UpdateItemContextMatching = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:450
 verticalFlyout = true
 SetItemButtonCount = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:614
 SetItemInternal = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:549
 UpdateCorruptedGlow = <function> defined @Interface/FrameXML/AzeritePaperDollItemOverlay.lua:3
 UpdateCraftedProfessionsQualityShown = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:461
 HighlightTexture = Texture {
 }
 PostOnEvent = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:427
 GetItemContextOverlayMode = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:471
 SetItemSource = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:528
 SetBagID = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:639
 UpdateItemContextOverlay = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:488
 ResetAzeriteItem = <function> defined @Interface/FrameXML/AzeritePaperDollItemOverlay.lua:67
 PushedTexture = Texture {
 }
 Count = CharacterSecondaryHandSlotCount {
 }
 SetItemButtonAnchorPoint = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:618
 searchOverlay = CharacterSecondaryHandSlotSearchOverlay {
 }
 NormalTexture = CharacterSecondaryHandSlotNormalTexture {
 }
 IconOverlay2 = Texture {
 }
 OnUpdateItemContextMatching = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:651
 OnItemContextChanged = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:410
 GetItemContextMatchResult = <function> defined @Interface/FrameXML/PaperDollFrame.lua:2775
 AvailableTraitFrame = Frame {
 }
 popoutButton = CharacterSecondaryHandSlotPopoutButton {
 }
 backgroundTextureName = 136524
 SetItemButtonScale = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:623
 isCraftedItem = false
 isProfessionItem = false
 Cooldown = CharacterSecondaryHandSlotCooldown {
 }
 BCPDisplay = Frame {
 }
 itemContextMatchResult = 3
 GetItemLocation = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:610
 GetSlotAndBagID = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:647
 DisplayAsAzeriteItem = <function> defined @Interface/FrameXML/AzeritePaperDollItemOverlay.lua:28
 SetAzeriteItem = <function> defined @Interface/FrameXML/AzeritePaperDollItemOverlay.lua:7
 AzeriteTexture = Texture {
 }
 GetItemID = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:591
 GetItemButtonCount = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:627
 SetItemButtonQuality = <function> define

**Comment by muleyo** [comment]
Seems to be working fine on my end.

**Comment by BlackandYoung** [comment]
On my evoker all its fine, but on my best mystery hunter and retribution paladin i have this bug...

**Comment by BlackandYoung** [comment]
its when i open "Character Info"

**Comment by muleyo** [comment]
Cant reproduce this error. Closed.

**Comment by BlackandYoung** [comment]
![image](https://github.com/Syiana/SUI/assets/147303050/f95ef8ad-2f53-4c7c-872e-1b99bb1d1e45)

**Comment by muleyo** [comment]
I still cannot reproduce this error, and you are still the only one who's reporting this issue. Please try re-installing SUI.

**Comment by BlackandYoung** [comment]
Ok thank you for help after 10.2.5 update sui all its good
I update its now and all its working thank u <3
