### ISSUE TITLE
I see nothing

### ISSUE THREAD

**Issue by FrankWhite73** [Syiana/SUI#150]
**Describe the bug**
When I type /sui the addon window opens but I just don't see anything in the window. Nothing is displayed.

I have not activated any other addons. Regards

**To Reproduce**

**Expected behavior**
To see the SUI Options in the SUI Window

**Screenshots**

**Which World of Warcraft version (please complete the following information):**
 - Retail
![sui](https://github.com/Syiana/SUI/assets/38111517/492ebf03-020a-4630-a31b-f4ec556c584d)

**Additional context**

**Comment by muleyo** [comment]
Please reset the SUI settings with the Curse Client or:

Navigate to: `World of Warcraft/_retail_/WTF/Account/<YourAccountID>/SavedVariables` and delete the files `SUI.lua` and `SUI.lua.bak`.

**Comment by FrankWhite73** [comment]
Hi cleanlock,
deleting the files helped. Thank you for your support. :)
