### ISSUE TITLE
[BUG] Castbars features

### ISSUE THREAD

**Issue by dev-wagner-zoccoli** [Syiana/SUI#151]
**Describe the bug**
Castbars: 1. the placement of the bar for target and focus is not working properly. It flashes between bottom and top when "top" is selected. 2. Also the scaling slider for focus is not working, the target slider changes both. 

**To Reproduce**
Placement feature:
1. In WoW, Select a focus target;
2. In the "Castbar On Top" section, check box for target or focus target;
3. Cast anything...
4. Watch erratic behavior.

Scale feature:
1. In WoW, Select a focus target;
2. In the "Castbar Scale" section, use the focus slider to adjust size;
3. Cast any spell and see that focus castbar size does not change;
4. Now use target slider to asdjust size;
5. cast any spell and see that it changes size of both castbars.

**Expected behavior**
When "top" is selected, for any of the frames, it shouldn't flash between positions (top/bottom), it should stick at the top of the frame.

**Screenshots**
[If applicable, add screenshots to help explain your problem.]
[video exemple](https://youtu.be/V7bD3v2l8Gk)

**Which World of Warcraft version (please complete the following information):**
 - Retail

**Additional context**
None.

**Comment by muleyo** [comment]
Hey, will look into it soon.

**Comment by muleyo** [comment]
This should be fixed with the latest version. Sorry for the delay.
