### ISSUE TITLE
[BUG] Patch!

### ISSUE THREAD

**Issue by Alesticus** [Syiana/SUI#152]
**There's nothing since the patch**
When i got the addon the button doesn't pop up on the menu and the slash command just gives an error. The text looks like SUI text and the player frame looks right though!

**To Reproduce**
1. Go to 'WoW'
2. Login
3. Nada :(

**Expected behavior**
It's a new patch, so this isn't entirely unexpected!

**Screenshots**
![Screenshot (1358)](https://github.com/Syiana/SUI/assets/169214142/a6cd2306-ff30-4562-acfb-9736e45ff564)

**Which World of Warcraft version (please complete the following information):**
 - Retail

**Additional context**
Lua Error: 
![image](https://github.com/Syiana/SUI/assets/169214142/5337ff95-f51e-4652-bdbd-78ccc29ef2f4)

**Comment by muleyo** [comment]
Hey, should be fixed with the latest update. Thanks for the report :)
