### ISSUE TITLE
[REQUEST] Chat editbox skin

### ISSUE THREAD

**Issue by illum1n4ti** [Syiana/SUI#153]
**Describe the bug**

**To Reproduce**
1. Go to 'line 90 in chat core.lua in chat module'
2. U need this !Beautycase. maybe u could add in ur embedded folder

      -- Chat skin
      for k = 3, 8 do
        select(k, _G[chat.."EditBox"]:GetRegions()):SetTexture(nil)
      end

      Mixin(_G[chat.."EditBox"], BackdropTemplateMixin)
      _G[chat.."EditBox"]:SetBackdrop({
          bgFile = "Interface\\Buttons\\WHITE8x8",
          insets = {
              left = 3, right = 3, top = 2, bottom = 2
          },
      })
    
      _G[chat.."EditBox"]:SetBackdropColor(0, 0, 0, 0.5)
      _G[chat.."EditBox"]:CreateBeautyBorder(11)
      _G[chat.."EditBox"]:SetBeautyBorderPadding(-2, -1, -2, -1, -2, -1, -2, -1)
      _G[chat.."EditBox"]:SetBeautyBorderTexture("white")

      hooksecurefunc("ChatEdit_UpdateHeader", function(editBox)
          local chatType = editBox:GetAttribute("chatType")
          if not chatType then
              return
          end

          local info = ChatTypeInfo[chatType]
          _G[chat.."EditBox"]:SetBeautyBorderColor(info.r, info.g, info.b)
      end)

**Expected behavior**

**Screenshots**
[url=https://ibb.co/rs7R6dT][img]https://i.ibb.co/GTx42HB/chatbar.png[/img][/url]
[url=https://ibb.co/S6qFyHp][img]https://i.ibb.co/mRQfTd7/chatbar-guild.png[/img][/url]

**Which World of Warcraft version (please complete the following information):**
 - Retail

**Additional context**
let me know if u need help :)

**Comment by muleyo** [comment]
Please make a pull request instead.
