### ISSUE TITLE
[BUG] No XP Bar with Small ActionBar

### ISSUE THREAD

**Issue by freshiz71** [Syiana/SUI#154]
**Describe the bug**
When Small ActionBar is active, there is not XP Bar or Reput Bar 
**To Reproduce**
1. Go to SUI Option
2. Click on Action Bar
3. Scroll down to Small
4. Save 

**Expected behavior**
Xp and Reput Bar should appears
**Screenshots**
![image](https://github.com/Syiana/SUI/assets/148541099/bff84f23-0af4-4a47-ad1c-a2f0893f347e)

**Which World of Warcraft version (please complete the following information):**
 - Vanilla SOD

**Additional context**

**Comment by muleyo** [comment]
intended.
