### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Drerunsit** [Syiana/SUI#155]
Hello. First, I just want to say that this is a great, minimalistic addon. I am absolutely loving it!

My issue is with the quest log. I can't see any settings in SUI that specifically address the Quest Log; however, right after I installed SUI, I noticed that it was visually glitched. As you can see from the screenshot, the text background spills beyond the border of the window, and there's a dark rectangle in the upper-left side.

![Screenshot 2024-06-12 112055](https://github.com/Syiana/SUI/assets/172521039/f8bfe99d-ac28-4bee-a306-c26de74e2947)

I am on WoW Classic, Season of Discovery. Thank you!

**Comment by muleyo** [comment]
outdated and not supported atm.
