### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Alesticus** [Syiana/SUI#156]
**Describe the bug**
a LUA error. When it pops the font and the buttons are just the default

**To Reproduce**
1. Login with any addons active with SUI
2. See error

**Expected behavior**

**Screenshots**

**Which World of Warcraft version (please complete the following information):**
 - Retail

![image](https://github.com/Syiana/SUI/assets/169214142/26a54661-c0a7-4845-a441-49288e77657a)

**Comment by Alesticus** [comment]
From everything I'm seeing it's just badly interacting with my other addons. Elephant, details, etc.

**Comment by muleyo** [comment]
will look into it.

**Comment by muleyo** [comment]
seems like an Details issue at this point. I tried to fix it, without success. No clue why Details has that issue tho.
