### ISSUE TITLE
[BUG] attempt to call global 'GetItemIcon' (a nil value)

### ISSUE THREAD

**Issue by michael-farwell** [Syiana/SUI#157]
When looting any item on the WarWithin Beta you get the following error:

Message: Interface/AddOns/SUI/Modules/Chat/_Core.lua:150: attempt to call global 'GetItemIcon' (a nil value)
Time: Sat Jun 29 08:38:51 2024
Count: 3
Stack: Interface/AddOns/SUI/Modules/Chat/_Core.lua:150: attempt to call global 'GetItemIcon' (a nil value)
[string "@Interface/AddOns/SUI/Modules/Chat/_Core.lua"]:150: in function <Interface/AddOns/SUI/Modules/Chat/_Core.lua:149>
[string "=[C]"]: in function `gsub'
[string "@Interface/AddOns/SUI/Modules/Chat/_Core.lua"]:154: in function `filterFunc'
[string "@Interface/AddOns/Blizzard_ChatFrameBase/Mainline/ChatFrame.lua"]:3749: in function `ChatFrame_MessageEventHandler'
[string "@Interface/AddOns/Blizzard_ChatFrameBase/Mainline/ChatFrame.lua"]:3283: in function `ChatFrame_OnEvent'
[string "@Interface/AddOns/Blizzard_ChatFrameBase/Mainline/FloatingChatFrame.lua"]:94: in function <...lizzard_ChatFrameBase/Mainline/FloatingChatFrame.lua:93>

Locals: link = "[Ironclaw Ore |A:Professions-ChatIcon-Quality-Tier1:17:15::1|a]"
(*temporary) = nil
(*temporary) = "[Ironclaw Ore |A:Professions-ChatIcon-Quality-Tier1:17:15::1|a]"
(*temporary) = "attempt to call global 'GetItemIcon' (a nil value)"

**Comment by muleyo** [comment]
cant reproduce.
