### ISSUE TITLE
[BUG] attempt to call global 'GetItemInfoInstant' (a nil value)

### ISSUE THREAD

**Issue by michael-farwell** [Syiana/SUI#158]
When opening the character panel in the WarWithin Beta, you get the following error:
Message: Interface/AddOns/SUI/Modules/General/_Itemlevel.lua:123: attempt to call global 'GetItemInfoInstant' (a nil value)
Time: Sat Jun 29 09:03:51 2024
Count: 6
Stack: Interface/AddOns/SUI/Modules/General/_Itemlevel.lua:123: attempt to call global 'GetItemInfoInstant' (a nil value)
[string "@Interface/AddOns/SUI/Modules/General/_Itemlevel.lua"]:123: in function <Interface/AddOns/SUI/Modules/General/_Itemlevel.lua:113>
[string "@Interface/AddOns/SUI/Modules/General/_Itemlevel.lua"]:311: in function <Interface/AddOns/SUI/Modules/General/_Itemlevel.lua:285>
[string "@Interface/AddOns/SUI/Modules/General/_Itemlevel.lua"]:411: in function <Interface/AddOns/SUI/Modules/General/_Itemlevel.lua:403>
[string "@Interface/AddOns/SUI/Modules/General/_Itemlevel.lua"]:414: in function <Interface/AddOns/SUI/Modules/General/_Itemlevel.lua:414>
[string "=[C]"]: in function `PaperDollItemSlotButton_Update'
[string "@Interface/AddOns/Blizzard_UIPanels_Game/Mainline/PaperDollFrame.lua"]:1579: in function <...s/Blizzard_UIPanels_Game/Mainline/PaperDollFrame.lua:1571>
[string "=[C]"]: in function `Show'
[string "@Interface/AddOns/Blizzard_UIParentPanelManager/Mainline/UIParentPanelManager.lua"]:483: in function `SetUIPanel'
[string "@Interface/AddOns/Blizzard_UIParentPanelManager/Mainline/UIParentPanelManager.lua"]:326: in function `ShowUIPanel'
[string "@Interface/AddOns/Blizzard_UIParentPanelManager/Mainline/UIParentPanelManager.lua"]:169: in function <...ParentPanelManager/Mainline/UIParentPanelManager.lua:164>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface/AddOns/Blizzard_UIParentPanelManager/Mainline/UIParentPanelManager.lua"]:861: in function `ShowUIPanel'
[string "@Interface/AddOns/Blizzard_UIPanels_Game/Mainline/CharacterFrame.lua"]:44: in function <...s/Blizzard_UIPanels_Game/Mainline/CharacterFrame.lua:24>
[string "=[C]"]: in function `ToggleCharacter'
[string "TOGGLECHARACTER0"]:1: in function <[string "TOGGLECHARACTER0"]:1>

Locals: unit = "player"
slot = 17
offHandItemLink = "[Earthen Traveler's Gavel]"
(*temporary) = 4
(*temporary) = nil
(*temporary) = "[Earthen Traveler's Gavel]"
(*temporary) = "attempt to call global 'GetItemInfoInstant' (a nil value)"
slotsThatHaveEnchants = <table> {
 7 = true
 1 = true
 15 = true
 8 = true
 16 = true
 9 = true
 5 = true
 11 = true
 6 = true
 12 = true
}

**Comment by muleyo** [comment]
cant reproduce.
