### ISSUE TITLE
Cata Classic - Party Frame HP bars

### ISSUE THREAD

**Issue by YourFalseHope** [Syiana/SUI#159]
I noticed my party frames no longer show when a party member's health bars shift. As a healer, this is quite uncomfortable. My raid frames appear to work, but when doing 5mans I have to disable the addon to see health bars.

**Comment by muleyo** [comment]
not SUI related. SUI does not touch the raidframe healthbars at all, except setting an texture and that code works like a charm on my end.

**Comment by YourFalseHope** [comment]
![Screenshot (349)](https://github.com/Syiana/SUI/assets/128880417/97456ed9-3cf6-43d2-a16e-61c29224fa6c)

This is what I am talking about. These are not raid frames, but the 5 man party frames. This image was taken with only SUI installed. As you can see the frames on the side do not show the damage taken by the other players in the party as highlighted in red.

**Comment by muleyo** [comment]
looking into it.

**Comment by YourFalseHope** [comment]
Thanks! Looks like it was last working in v4.4.30

**Comment by muleyo** [comment]
Fixed in the latest update.
