### ISSUE TITLE
[Suggestion] Totally hide micromenu/bags

### ISSUE THREAD

**Issue by HuMa69** [Syiana/SUI#161]
Can you add an option to completly hide micromenu and bagbars? mouseover its ok but many people like me have details on that corner of the screen...

**Comment by muleyo** [comment]
added.

**Comment by HuMa69** [comment]
thanks for bring back this great addon!

**Comment by muleyo** [comment]
you're welcome

**Comment by HuMa69** [comment]
theres a talent button and LFG in the middle of the screen when you hide microbar xD

![image](https://github.com/Syiana/SUI/assets/23564552/f65b7a1a-47ea-4ac2-88ad-319e031a6188)

**Comment by HuMa69** [comment]
and also lua error 
![image](https://github.com/Syiana/SUI/assets/23564552/e69d54cd-93b1-40c5-a153-562130ac292c)

**Comment by HuMa69** [comment]
And the xp bar its now shorter than the action bar

**Comment by muleyo** [comment]
I'm working on it :)

**Comment by muleyo** [comment]
Should be fixed now, I don't see any errors anymore with the latest AddOn build.
