### ISSUE TITLE
[BUG] UI error when queue to BG/Winter/Tolbarad

### ISSUE THREAD

**Issue by HuMa69** [Syiana/SUI#163]
![image](https://github.com/Syiana/SUI/assets/23564552/5f6101ff-c4d1-472a-b4a9-c8e79db3060e)

basically this, even reloggin or reloading doesnt fix it, you have to disable SUI then queue and enable it again

**Comment by muleyo** [comment]
I don't have that issue at all.. when exactly does this happen? If you press buttons or target someone?

**Comment by HuMa69** [comment]
when trying to queue to any bg, winter or tolbarad, couldnt test in arenas cause im just leveling an alter now

**Comment by muleyo** [comment]
I dont have that issue at all then idk. You got some other weird addon for queueing or something? Cux SUI literally does nothing there except changing button colors etc., nothing what would taint.
