### ISSUE TITLE
SUI microbar and dungeon eye vanishing

### ISSUE THREAD

**Issue by Alesticus** [Syiana/SUI#164]
So this has been going on for awhile for me, i've been using bartender with SUI just to fix it but I thought I'd throw it in here as I'd really like to get rid of it. I login, everything is normal but the moment I start doing stuff, anything in WoW, my microbar and the dungeon queue eye vanishes. If I /reload it comes right back up, but then I go back to playing and it just happens again.

**Comment by muleyo** [comment]
Should be fixed.
