### ISSUE TITLE
[BUG] Reset of player frame when reloading UI

### ISSUE THREAD

**Issue by VintherMN** [Syiana/SUI#165]
**Describe the bug**
Whenever i reload my UI, or just log into my character, the position of the playerframe is always reset to be at the default position.

**To Reproduce**
1. Move player frame to anywhere but the default position
2. /rl or /reload UI
3. Watch the player frame jump to the default position

(Ive tested this with only SUI enabled, no other addons)

**Expected behavior**
I expect the player frame to stay fixed where i have locked it.

**Screenshots**
First screenshot: locked player frame at the position where i want it to be
https://imgur.com/a/Q4jtAVH
Second Screenshot: After reloading ui (frame still locked but reset position)
https://imgur.com/a/0fIYPFP

**Which World of Warcraft version (please complete the following information):**
 - Classic Era (Season of Discovery)

**Additional context**

**Comment by VintherMN** [comment]
I have no idea if it just an issue on my end, but its an issue that slowly forcing me to move away from this UI pack.
Another thing to add, is that my player frame is not reset when i have SUI disabled. Frames stay after reload.

**Comment by VintherMN** [comment]
Update (this makes me feel stupid, but im gonna leave this bug issue here)
The bug only happens when trying to move frame with blizzard default "unlock frame" method. I just moved it using the "edit" method in the UI, and player frame stay after reloading - maybe look into integrating the blizzard default move frame method, because surely i wont be the last to hit this issue.

**Comment by muleyo** [comment]
That's how SUI works, unfortunately. We only support moving through our own Edit mode.
