### ISSUE TITLE
[BUG] not compatible with Clique addon

### ISSUE THREAD

**Issue by Grimickles** [Syiana/SUI#169]
**Describe the bug**
The add-on
![how its supposed to look](https://github.com/user-attachments/assets/4f356e7e-e884-4386-a56c-31ba75121312)
 keeps giving me LUA errors due to the issue in the picture below.

**To Reproduce**
1.install clique addon
2. See error

**Expected behavior**
Not sure if this quite your problem or not, figured i'd route it up.

**Screenshots**
Problem: 
![problem 1](https://github.com/user-attachments/assets/3fdaa621-fd28-455b-a95b-e689cc2d2a32)

**Which World of Warcraft version (please complete the following information):**
 - Retail

**Comment by muleyo** [comment]
It's a problem with 'LibDropDown'. SUI and Clique are using that library and that's why it's causing issues when both AddOns are loaded at the same time. Nothing we can do about it.

**Comment by Grimickles** [comment]
Ah, cool thanks for the quick reply.
