### ISSUE TITLE
[BUG] LUA Error - Guild friend list

### ISSUE THREAD

**Issue by OjunbamO** [Syiana/SUI#17]
**Describe the bug**
First Hi,
I think I am the only person experiencing this because otherwise it would get fixed. In classic WoW I decided yesterday to join a guild. Since that I am constantly getting the same lua error. Every like 2-5min or instantly if I open the friend list/social interface. I already disabled all other addons to see if it has a conflict but it still exists. I tried to switch versions from 3.16 until 3.14 but all result the same error.

**To Reproduce**
1. Just press O in my case...

**Expected behavior**
To not have the lua error window anymore. For sure I found the "/console scriptErrors 0" command which prohibits the opening of the window. But it is still annoying because I have to press the macro every time I reload/restart the game...

**Screenshots**
![WoWSui-UIError](https://user-images.githubusercontent.com/11799007/197502228-1a326a72-6db1-49ce-afef-129cee3980d2.png)

**Log**
```
Message: Interface\AddOns\SUI\Modules\Chat\_Friendlist.lua:159: attempt to index local 'classc' (a nil value)
Time: Mon Oct 24 11:51:34 2022
Count: 1
Stack: Interface\AddOns\SUI\Modules\Chat\_Friendlist.lua:159: attempt to index local 'classc' (a nil value)
[string "@Interface\AddOns\SUI\Modules\Chat\_Friendlist.lua"]:159: in function `GuildColor_Class'
[string "@Interface\AddOns\SUI\Modules\Chat\_Friendlist.lua"]:323: in function <Interface\AddOns\SUI\Modules\Chat\_Friendlist.lua:281>
[string "=[C]"]: in function `FriendsList_Update'
[string "@Interface/FrameXML/FriendsFrame_Shared.lua"]:1116: in function `FriendsFrame_CheckBattlenetStatus'
[string "@Interface_Wrath\FrameXML\FriendsFrame_Wrath.lua"]:134: in function `FriendsFrame_OnEvent'
[string "*:OnEvent"]:1: in function <[string "*:OnEvent"]:1>

Locals: playerzone = "Sturmwind"
off = 0
(for index) = 1
(for limit) = 13
(for step) = 1
i = 1
name = "Spaghettisul-Everlook"
_ = "Flüssiges Brot"
_ = 9
level = 48
class = "Krieger"
zone = "Sturmwind"
_ = ""
_ = ""
online = true
classc = nil
(*temporary) = <function> defined =[C]:-1
(*temporary) = GuildFrameGuildStatusButton1Name {
 0 = <userdata>
}
(*temporary) = "1"
(*temporary) = "Name"
(*temporary) = "PALADIN"
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'classc' (a nil value)"
```

**Which World of Warcraft version (please complete the following information):**
 - Wotlk

Hope you can help me. It is not that important but would be cool to get this fixed. Also I think it is a problem with only my wow instance so reinstalling wotlk would help I think....

Thanks in advance!

Regards
OjunbamO

**Comment by muleyo** [comment]
Closed as classic is not supported anymore
