### ISSUE TITLE
[BUG] Numbers/Text inside Buff frames is bugged.

### ISSUE THREAD

**Issue by winternite** [Syiana/SUI#170]
There is an issue with the buff frame where the text (if remaining time left on a buff like battle shout) is inside the box, this issue is happening to me in both Cata and Retail.

This is naturally with everything disabled except for SUI.

![Screenshot 2024-07-28 001414](https://github.com/user-attachments/assets/e6b6d3a5-acb0-4093-a45c-b54f5a488e24)

**Comment by muleyo** [comment]
Not a bug, thats intended.
