### ISSUE TITLE
[BUG]won't work

### ISSUE THREAD

**Issue by Ayawni** [Syiana/SUI#173]
I have tried everything I could but it won't run. when I open the /SUI it just show blank black sheet, and nothing else. I really like SUI, makes me so sad that it would not run on me. please help me!!!! thank you .!

**Screenshots**
![(BEA93E(6JC_E%FF0 1HN0J](https://github.com/user-attachments/assets/1652bb19-61b2-4049-96b8-2dd3af08aa42)

**Which World of Warcraft version (please complete the following information):**
 - Retail

**Comment by muleyo** [comment]
Reset SUI settings.

Either through Curse Client or delete the following files:

`World of Warcraft\_retail_\WTF\Account\<YOURACCOUNT>\SavedVariables\SUI.lua`
`World of Warcraft\_retail_\WTF\Account\<YOURACCOUNT>\SavedVariables\SUI.lua.bak`
