### ISSUE TITLE
[BUG] Can't hidde the class bar when using the default texture

### ISSUE THREAD

**Issue by megastanou** [Syiana/SUI#175]
Hi !

**Describe the bug**
In the unitframes menu, when i use the default texture, i can't hide the class bar, DK frost runes in my casse.  
As soon as i pick for another texture the class bar is removed. 

**Screenshots**
![image](https://github.com/user-attachments/assets/99af7621-b794-44ce-8cf9-6defc085e632)

**Which World of Warcraft version (please complete the following information):**
 - Retail

Thanks for your addon, it's verry cool !

**Comment by muleyo** [comment]
Fixed
