### ISSUE TITLE
[BUG] Target unitframe name text dissapears,LFG eye missing

### ISSUE THREAD

**Issue by Popikaify** [Syiana/SUI#176]
**Describe the bug**

If i target someone,unitframe target name will simply dissapear and show somewhere else and this mostly happens when in combat,also if i que up in LFG the eye never shows up unless i disable the addon.

**Screenshots**

![WoWScrnShot_082424_125940](https://github.com/user-attachments/assets/807f2c02-09a7-43d6-856e-601dfa837787)

Name appeared near the stormwind guard on the left side

**Which World of Warcraft version (please complete the following information):**
 - Retail

**Comment by muleyo** [comment]
if the LFG eye is missing, reset SUI settings and adjust the position within the game's EditMode.

Unitframe Text has been fixed.
