### ISSUE TITLE
[BUG] Dungeon Eye in the middle of the Screen

### ISSUE THREAD

**Issue by bswebdes** [Syiana/SUI#177]
**Describe the bug**
Dungeon Eye in the middle of the Screen

**Screenshots**
![WoWScrnShot_082524_092313](https://github.com/user-attachments/assets/feb28ae3-722a-4e3f-880f-aaa312a04745)

**Which World of Warcraft version (please complete the following information):**
 - Retail

**Comment by IvanAleksandrov94** [comment]
> **Describe the bug** Dungeon Eye in the middle of the Screen
> 
> **Screenshots** ![WoWScrnShot_082524_092313](https://private-user-images.githubusercontent.com/109763429/361192533-feb28ae3-722a-4e3f-880f-aaa312a04745.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2NjkyMzgsIm5iZiI6MTcyNDY2ODkzOCwicGF0aCI6Ii8xMDk3NjM0MjkvMzYxMTkyNTMzLWZlYjI4YWUzLTcyMmEtNGUzZi04ODBmLWFhYTMxMmEwNDc0NS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyNlQxMDQyMThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYTZiOTYwYjU2M2JkODJlY2QwMmIwZDQ2YjkwYWIwZGNiODFjZWRkODA0MWY3MWQ3NjcyZmRkOWU5ZTdlZmJhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8qgXXL0mRhZP5kyYyOZQlDSBTNU1izGhp5sN-CN_Djo)
> 
> **Which World of Warcraft version (please complete the following information):**
> 
> * Retail

You can customize the location of the icon yourself through the Blizzard edit menu.

![photo_2024-08-26_13-38-49](https://github.com/user-attachments/assets/cbef0791-5c09-4612-a896-ff3e6733d04e)

**Comment by bswebdes** [comment]
> > **Describe the bug** Dungeon Eye in the middle of the Screen
> > **Screenshots** ![WoWScrnShot_082524_092313](https://private-user-images.githubusercontent.com/109763429/361192533-feb28ae3-722a-4e3f-880f-aaa312a04745.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2NjkyMzgsIm5iZiI6MTcyNDY2ODkzOCwicGF0aCI6Ii8xMDk3NjM0MjkvMzYxMTkyNTMzLWZlYjI4YWUzLTcyMmEtNGUzZi04ODBmLWFhYTMxMmEwNDc0NS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyNlQxMDQyMThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYTZiOTYwYjU2M2JkODJlY2QwMmIwZDQ2YjkwYWIwZGNiODFjZWRkODA0MWY3MWQ3NjcyZmRkOWU5ZTdlZmJhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8qgXXL0mRhZP5kyYyOZQlDSBTNU1izGhp5sN-CN_Djo)
> > **Which World of Warcraft version (please complete the following information):**
> > 
> > * Retail
> 
> You can customize the location of the icon yourself through the Blizzard edit menu.

Oh gosh...
Yep... thanks mate. My bad-.-
