### ISSUE TITLE
Whats default font?

### ISSUE THREAD

**Issue by hallhoward221** [Syiana/SUI#179]
I have messed up with another font and wanna change it back to default. Before 'font' bar was empty. Whats that 'empty' font ?
![image](https://github.com/user-attachments/assets/721108ad-fd14-4956-b6fa-fbc690efe802)
But 'Default' and 'Frizz TT' arent that font 'blank'. Chat arent bold like before

PS okay it probably was SUI font, but on ru locale it doesnt inside options.
Had to make changes 
`LSM:Register("font", "SUI", [[Interface\Addons\SUI\Media\Fonts\Prototype.ttf]])`
adding `bit.bor(LSM.LOCALE_BIT_western, LSM.LOCALE_BIT_ruRU)` at the end after comma

**Comment by muleyo** [comment]
Default font = Game font.

SUI = Prototype.
