### ISSUE TITLE
[BUG] Target of Target disappears

### ISSUE THREAD

**Issue by Drerunsit** [Syiana/SUI#181]
For several weeks now, the Target of Target frame disappears and does not come back until I log out and log back in. Then it's gone again in a few minutes or less. I have disabled SUI and the issue does not replicate when it is disabled. I am WoW Classic SOD.

**Comment by muleyo** [comment]
We're not doing anything to the ToT frame itself, we only change the healthbar color to classcolor, and we didn't receive any other reports about that issue so I'd say it's not an SUI issue.

**Comment by Drerunsit** [comment]
When I disable SUI, the problem disappears. Maybe it's an interaction between SUI and another addon, but SUI is definitely involved.
