### ISSUE TITLE
[BUG] No EXP-Bar - Small Actionbar

### ISSUE THREAD

**Issue by PicassoMio** [Syiana/SUI#183]
**Describe the bug**
Unfortunately, no experience bar is displayed when you use small actionbars. "Show Exp Bar" Button on misc tap is checked.

**To Reproduce**

1. hit escape to bring up the main menu
2. open SUI at the top
3. Actionbar
4. Select "Small" Actionbar
5. Misc
6. Select/check "Show Exp Bar"

**Comment by muleyo** [comment]
Make sure to move the Actionbars slightly up as the Experience bar is right below. If your bars are at the bottom of your screen, it wont be visible.
