### ISSUE TITLE
[BUG] Options not loading properly after importing a profile from wow classic cata.

### ISSUE THREAD

**Issue by mondayqq** [Syiana/SUI#185]
**Describe the bug**
Options not loading properly after importing a profile from wow classic cata.

**To Reproduce**
1. copy profile from cata calssic wow
2. import copyed cata classic wow profile into retail wow
3. See error (options not loading)

**Screenshots**
![image](https://github.com/user-attachments/assets/4ad08a47-13d2-4ce7-8bc1-2c22f02ceb23)

**Which World of Warcraft version (please complete the following information):**
 - Retail 
 - Cata classic

**Comment by mondayqq** [comment]
Fixed - I just deleted the daved variables so it clean installes.

**Comment by muleyo** [comment]
This is not a bug. SUI Cata and SUI Retail are different, profiles cannot be shared between Cata and Retail.
