### ISSUE TITLE
[BUG] Waist "No Enchant" in TWW

### ISSUE THREAD

**Issue by MilkKrate** [Syiana/SUI#186]
**Describe the bug**
The character pane says "No Enchant" on waists while level 80. There is not belt enchant at level 80

**To Reproduce**
1. Open the character pane on a level 80 character.
2. Equip a belt.
4. See "No Enchant" message next to waist 

**Expected behavior**
Should not see a "No Enchant" message next to waist when level 80.

**Screenshots**
![image](https://github.com/user-attachments/assets/159c14d0-cfac-4ff3-ae19-2e38d475cdc0)

**Which World of Warcraft version (please complete the following information):**
 - Retail

**Additional context**
None needed.

**Comment by muleyo** [comment]
You should update SUI... that's been fixed a while ago.

**Comment by MilkKrate** [comment]
Wow. I feel stupid. My addon app wasn't tracking SUI. Manaully added it and update. Works perfect. Thanks for the help!
