### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Twistt3r** [Syiana/SUI#187]
hello, I have a bug with the energy bar which is black, it does not move depending on the energy spent. It conflicts with the RaidFrameSettings add-on  

(Played on Retail, all addons are updates)

https://www.curseforge.com/wow/addons/raid-frame-settings/comments

![Capture d'écran 2024-10-15 195945](https://github.com/user-attachments/assets/fcf9ca24-da11-4b29-9adc-b8676f26914c)

**Comment by muleyo** [comment]
Not SUI related. Make sure to disable the texture module in RFS.
