### ISSUE TITLE
[BUG] Addon disables queue status eye after reload.

### ISSUE THREAD

**Issue by Qarciva** [Syiana/SUI#188]
**Describe the bug**
Addon disables queue status eye after reload.

**Expected behavior**
on screenshot you can see i'm in que but there is no eye.

**Screenshots**
![Untitled](https://github.com/user-attachments/assets/91efecaf-b6ef-418b-9f4d-b1d81defac4a)

**Which World of Warcraft version (please complete the following information):**
 - Retail

**Additional context**
Love this addon and please fix it :*

**Comment by muleyo** [comment]
Reset your SUI settings please and make sure to not use any actionbar AddOn with SUI (such as Bartender or Dominos) as those also change the Queue Icon's position and they conflict at the moment.

**Comment by Qarciva** [comment]
> Reset your SUI settings please and make sure to not use any actionbar AddOn with SUI (such as Bartender or Dominos) as those also change the Queue Icon's position and they conflict at the moment.

Reset helped.thank you <3
