### ISSUE TITLE
SUI not working properly

### ISSUE THREAD

**Issue by Birchsen12** [Syiana/SUI#20]
Hi,
First of all, ty for this amazing addon, makes the game look so much better. 
I logged in today, and the SUI was not applied to the UI, tried reloading it, didnt do anything. Is the addon just not updated yet, or do i have an issue? Not rushing you if its just not updated, just want it clarified before i go change to another addon! 
Ty again :)

**Comment by Syiana** [comment]
Hey,

SUI is at the moment not released for 10.0

We already working on an update!

**Comment by Cempres** [comment]
Do we have an ETA for the v10 update?

**Comment by muleyo** [comment]
> Do we have an ETA for the v10 update?

1-2 weeks max. Feel free to sub to Syiana/me on Twitch or support us on Patreon for Beta access. :)

**Comment by muleyo** [comment]
Release will be on November 16th.
