### ISSUE TITLE
[BUG] Buffs (at Minimap) clipping into Debuffs - WotLK Version

### ISSUE THREAD

**Issue by Phil1326** [Syiana/SUI#25]
I currently have no screenshot, but basically whenever I raid, the buffs will at some point clip into the debuffs (even with a pretty large number set per row), making it basically impossible to see what debuffs I have. (problematic on Thaddius for example).

**Which World of Warcraft version (please complete the following information):**
 - Wotlk

**Comment by muleyo** [comment]
Not a bug. Please move the Debuff frame further down if it's clipping into your buff frame. You can do that by pressing "Edit" in the SUI menu.
