### ISSUE TITLE
[BUG] LUA ERROR - Bags (RETAIL)

### ISSUE THREAD

**Issue by kod-luis** [Syiana/SUI#26]
The bug happens when you click the npc on the mount (see attached image).
It happened with the "one bag" mode and the normal mode as well.
While I'm here if possible to move or make it moveble the "eye" as you see in the image.. is kinda off the map

![image](https://user-images.githubusercontent.com/11357262/202201795-90c359bb-7dcf-409f-be85-bd6be1e032fb.png)

Message Error

Message: Interface/AddOns/SUI/Modules/General/_Sell.lua:11: attempt to call global 'GetContainerNumSlots' (a nil value)
Time: Wed Nov 16 11:03:47 2022
Count: 4
Stack: Interface/AddOns/SUI/Modules/General/_Sell.lua:11: attempt to call global 'GetContainerNumSlots' (a nil value)
[string "@Interface/AddOns/SUI/Modules/General/_Sell.lua"]:11: in function <Interface/AddOns/SUI/Modules/General/_Sell.lua:8>

Locals: bag = nil
slot = nil
(for index) = 0
(for limit) = 4
(for step) = 1
bag = 0
(*temporary) = 0
(*temporary) = nil
(*temporary) = 0
(*temporary) = "attempt to call global 'GetContainerNumSlots' (a nil value)"

**Comment by muleyo** [comment]
Fixed
