### ISSUE TITLE
[BUG] Lua Error - Tooltip skins

### ISSUE THREAD

**Issue by EloosiveFail** [Syiana/SUI#27]
Lua Error

Message: ...rface/AddOns/SUI/Modules/Skins/Blizzard/_Tooltip.lua:24: attempt to index field 'NineSlice' (a nil value)
Time: Wed Nov 16 11:52:37 2022
Count: 20
Stack: ...rface/AddOns/SUI/Modules/Skins/Blizzard/_Tooltip.lua:24: attempt to index field 'NineSlice' (a nil value)
[string "=[C]"]: ?
[string "@Interface/AddOns/SUI/Modules/Skins/Blizzard/_Tooltip.lua"]:24: in function <...rface/AddOns/SUI/Modules/Skins/Blizzard/_Tooltip.lua:6>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `securecallfunction'
[string "@Interface/SharedXML/Tooltip/TooltipDataHandler.lua"]:60: in function <Interface/SharedXML/Tooltip/TooltipDataHandler.lua:55>
[string "@Interface/SharedXML/Tooltip/TooltipDataHandler.lua"]:80: in function <Interface/SharedXML/Tooltip/TooltipDataHandler.lua:76>
[string "@Interface/SharedXML/Tooltip/TooltipDataHandler.lua"]:116: in function <Interface/SharedXML/Tooltip/TooltipDataHandler.lua:106>
[string "=[C]"]: in function `resume'
[string "@Interface/AddOns/TellMeWhen/TellMeWhen.lua"]:2800: in function <Interface/AddOns/TellMeWhen/TellMeWhen.lua:2761>

Locals:

**Comment by muleyo** [comment]
Fixed
