### ISSUE TITLE
[BUG] Tooltip Backdrop

### ISSUE THREAD

**Issue by Lanacan** [Syiana/SUI#32]
Retail Version

Message: ...rface/AddOns/SUI/Modules/Skins/Blizzard/_Tooltip.lua:56: attempt to index global 'backdrop' (a nil value)
Time: Fri Nov 18 08:22:55 2022
Count: 1

![image](https://user-images.githubusercontent.com/276962/202727464-9cc70e9a-e3a5-4145-9a53-98ca8b8e855c.png)

**Comment by muleyo** [comment]
Fixed
