### ISSUE TITLE
Dark theme on Action Bars?

### ISSUE THREAD

**Issue by Maximos7** [Syiana/SUI#33]
Hello. I use the Dark Theme or the custom with full black color but Action bars do not change? Anyway i can make it work cause its very important to me :) Thank you!

**Comment by Naughtynurse** [comment]
There is a weakaura called Chonky Blizzard UI Adjustments, it will make the background of actionbars black.
I know this becasue it did to mine and took me FOREVER to figure out why they were black backgrounds when i didn't want them to be.

Might try that route.

**Comment by Maximos7** [comment]
> 

Ty ma friend i ll check it. I can do it using Bartender+Masque but im trying to not overuse addons. Same goes for WAs. WAs are very PC heavy :/

**Comment by Syiana** [comment]
@Maximos7 any screenshots? actionbars should be black.

Also I do not know retail or classic?
Did you try disable all other Addons?

**Comment by Maximos7** [comment]
> @Maximos7 any screenshots? actionbars should be black.
> 
> Also I do not know retail or classic? Did you try disable all other Addons?

Its on retail but it works now after the updates. So its ok!

**Comment by Syiana** [comment]
Thanks for the information!
