### ISSUE TITLE
[BUG] Lua Error

### ISSUE THREAD

**Issue by EloosiveFail** [Syiana/SUI#34]
Message: ...rface/AddOns/SUI/Modules/Skins/Blizzard/_Tooltip.lua:56: attempt to index global 'backdrop' (a nil value)
Time: Sat Nov 19 12:17:56 2022
Count: 4
Stack: ...rface/AddOns/SUI/Modules/Skins/Blizzard/_Tooltip.lua:56: attempt to index global 'backdrop' (a nil value)
[string "=[C]"]: ?
[string "@Interface/AddOns/SUI/Modules/Skins/Blizzard/_Tooltip.lua"]:56: in function <...rface/AddOns/SUI/Modules/Skins/Blizzard/_Tooltip.lua:36>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `securecallfunction'
[string "@Interface/SharedXML/Tooltip/TooltipDataHandler.lua"]:60: in function <Interface/SharedXML/Tooltip/TooltipDataHandler.lua:55>
[string "@Interface/SharedXML/Tooltip/TooltipDataHandler.lua"]:80: in function <Interface/SharedXML/Tooltip/TooltipDataHandler.lua:76>
[string "@Interface/SharedXML/Tooltip/TooltipDataHandler.lua"]:116: in function <Interface/SharedXML/Tooltip/TooltipDataHandler.lua:106>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface/SharedXML/Tooltip/TooltipDataHandler.lua"]:141: in function <Interface/SharedXML/Tooltip/TooltipDataHandler.lua:134>
[string "@Interface/SharedXML/Tooltip/TooltipDataHandler.lua"]:282: in function <Interface/SharedXML/Tooltip/TooltipDataHandler.lua:240>
[string "=[C]"]: in function `securecallfunction'
[string "@Interface/SharedXML/Tooltip/TooltipDataHandler.lua"]:237: in function <Interface/SharedXML/Tooltip/TooltipDataHandler.lua:236>
[string "=(tail call)"]: ?
[string "@Interface/AddOns/TitanRepair/TitanRepair.lua"]:629: in function `TitanRepair_GetStatus'
[string "@Interface/AddOns/TitanRepair/TitanRepair.lua"]:488: in function `TitanRepair_GetInventoryInformation'
[string "@Interface/AddOns/TitanRepair/TitanRepair.lua"]:369: in function `TitanPanelRepairButton_OnUpdate'
[string "@Interface/AddOns/TitanRepair/TitanRepair.lua"]:324: in function `TitanPanelRepairButton_OnEvent'
[string "@Interface/AddOns/TitanRepair/TitanRepair.lua"]:1574: in function <Interface/AddOns/TitanRepair/TitanRepair.lua:1573>

**Comment by muleyo** [comment]
Fixed
