### ISSUE TITLE
[BUG]Addon getting blocked by WoW Retail

### ISSUE THREAD

**Issue by JugoBetrugoTV** [Syiana/SUI#35]
The Error appears after some minutes while playing a few rounds Arena.
I just use SUI + Details.
Even without Details i get the same bug - kinda annoying while playing Arena tho.

WoW Retail

![image](https://user-images.githubusercontent.com/118689854/202922892-12c57b29-ee54-4b35-a01f-f9a6133af104.png)

**Comment by Syiana** [comment]
@JugoBetrugoTV can u please download the Addons Bugsack and Buggrabber, after that you will get more details about the error.

**Comment by muleyo** [comment]
Should be fixed. Please check and report back to us. Thanks

**Comment by JugoBetrugoTV** [comment]
Hey, i didnt received the error since few days ago.
Should be fixed i guess :)
