### ISSUE TITLE
[BUG] Latest Update Debuff LUA errors

### ISSUE THREAD

**Issue by Naughtynurse** [Syiana/SUI#36]
**Describe the bug**
Constant LUA errors for debuffs. If left unattended, the number of errors will reach into the thousands,.
**To Reproduce**

**Expected behavior**

**Screenshots**
![error](https://user-images.githubusercontent.com/118778975/203177789-27803e0a-8681-4cae-aa53-e7b2967aaac5.JPG)

**Which World of Warcraft version (please complete the following information):**
 - Retail       X
 - Wotlk
 - Tbc
 - Vanilla

**Additional context**

**Comment by muleyo** [comment]
Fixed.

**Comment by Naughtynurse** [comment]
After your fix..I am no lnger getting "border" a nil value....it now says "icon" a nil value.

![image](https://user-images.githubusercontent.com/118778975/203856795-1e83394c-9808-4c25-ba7f-058cf2c1b1ba.png)

**Comment by Naughtynurse** [comment]
I am terribly sorry to have wasted your time. This error was being caused by a weakaura trying to modify the backgrounds of my buffs/debuffs. 

I am sure you are super busy with all this and I hate I wasted your time. Thanks for keeping up on this addon!

**Comment by muleyo** [comment]
No worries, glad you figured it out. :)
