### ISSUE TITLE
In-queue eye button is gone.

### ISSUE THREAD

**Issue by Lizezzy** [Syiana/SUI#38]
Hello,

Queue button in completely gone, when i disable SUI its there, but with the addon its gone.
I'm using Sexymap, and that addon completely deletes the original games map, in case the eye button is supposed to be on the old place. Atm i have to disable SUI just to leave queue and then put its back on, which isn't ideal.

Kind regards,
Lizzy G.

**Comment by muleyo** [comment]
You have to disable your Minimap addon.

**Comment by Lizezzy** [comment]
That was a risky move to put the button back to old place, knowing that no veteran wow gamer plays with 1 addon at the time.
Ig choices have to be made. Sad times for many players, that waited SUI update and now cannot use it cuz of this reason or another.

Goodbye then!

**Comment by muleyo** [comment]
This should be resolved with the latest update.
