### ISSUE TITLE
Anyone else getting this issue while in a raid group?

### ISSUE THREAD

**Issue by kevincuomo** [Syiana/SUI#42]
1x [ADDON_ACTION_BLOCKED] AddOn 'SUI' tried to call the protected function 'OverrideActionBarButton4:SetAttribute()'.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `SetAttribute'
[string "@FrameXML/ActionButton.lua"]:350: in function `UpdatePressAndHoldAction'
[string "@FrameXML/ActionButton.lua"]:412: in function `Update'
[string "@FrameXML/ActionButton.lua"]:362: in function `UpdateAction'
[string "@FrameXML/ActionButton.lua"]:821: in function `OnEvent'
[string "@FrameXML/ActionButton.lua"]:216: in function <FrameXML/ActionButton.lua:213>

**Comment by muleyo** [comment]
Definitely not caused by SUI. We don't use this function.
