### ISSUE TITLE
[BUG] Name Plates Core, non stop 'unpack' errors.

### ISSUE THREAD

**Issue by cpfowler** [Syiana/SUI#46]
**Describe the bug**
A clear and concise description of what the bug is:

Something to do with nameplates. While near the training dummies in Stormwind, frames are dropped non stop, and the counter for the bugs is going crazy.

from bugsack/buggrabber:

1493x SUI/Modules/NamePlates/_Core.lua:43: bad argument #1 to 'unpack' (table expected, got no value)
[string "=[C]"]: in function `unpack'
[string "@SUI/Modules/NamePlates/_Core.lua"]:43: in function <SUI/Modules/NamePlates/_Core.lua:7>
[string "@SUI/Modules/NamePlates/_Core.lua"]:144: in function <SUI/Modules/NamePlates/_Core.lua:49>
[string "=[C]"]: ?

Locals:
(*temporary) = "table expected, got no value"

**To Reproduce**
![image](https://user-images.githubusercontent.com/77090074/204067586-38eb05aa-8969-4ca4-aac7-bca56ecbb92e.png)

**Which World of Warcraft version (please complete the following information):**
 - Retail

Let me know if you need anymore info.

**Comment by muleyo** [comment]
Should be fixed in the next update.
