### ISSUE TITLE
[Suggestion] Moveable Castbars & DR Tracker / CD Tracker [Retail]

### ISSUE THREAD

**Issue by JugoBetrugoTV** [Syiana/SUI#48]
Hi,

i would suggest a moveable Castbar for Player/Target/Focus.
And a DR Tracker for the Enemy Arenaframes (im not 100% sure right now if there is a Trinket Tracker - but if not that would also be a good option).
Aswell as a CD Tracker for Group Mates

So there is no need to download Gladius or anything similar.

**Comment by muleyo** [comment]
Not gonna happen.
