### ISSUE TITLE
Buff borders

### ISSUE THREAD

**Issue by kod-luis** [Syiana/SUI#52]
Hello, i've noticed that when using the vertical buffs from blizzard the borders go wrong on the buffs, as you can see in the image bellow

![image](https://user-images.githubusercontent.com/11357262/204118836-11882fb2-39bb-4fa5-b894-2e82c9d4a1c3.png)

**Comment by neonvoidx** [comment]
same with horizontal buffs
![image](https://user-images.githubusercontent.com/25580051/204355113-ded99ead-c8e9-4c20-8889-1c0d4f9c914c.png)

**Comment by muleyo** [comment]
This is known. We might add it in the future, however it has low priority as most people have the buffs in the top right corner.

**Comment by neonvoidx** [comment]
But it's still bugged regardless of where buffs are on screen

**Comment by muleyo** [comment]
We only support Icon Wrap "Down" / Icon Direction "Left" at the moment.

**Comment by Friedcheese** [comment]
Hope it gets fixed soon, this addon is the perfect successor to lorti ui.
![Untitled](https://user-images.githubusercontent.com/23441935/205334444-b6a8d264-135a-4034-9ebd-310764150b31.jpg)

**Comment by muleyo** [comment]
I'll look into this later today.

**Comment by muleyo** [comment]
Fixed with the latest update.
