### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by GWEMLINN** [Syiana/SUI#65]
**Describe the bug**

**To Reproduce**
1. Type /sui into chat
2. scroll through menus to see that none of them are producing text in any way

**Expected behavior**
for the ui to be working at some base level as well as  being able to use the ui menu in some form.
the credits section does seem to show names though.
![image](https://user-images.githubusercontent.com/119634443/205173891-248c1195-d16b-404d-a5a4-12791a1ba0df.png)

**Screenshots**
![image (1)](https://user-images.githubusercontent.com/119634443/205173947-5f1a42a7-a5f8-434e-95ab-29a7720cd1b7.png)

**Which World of Warcraft version (please complete the following information):**
 - Retail

**Additional context**

**Comment by muleyo** [comment]
You need to delete your SavedVariables SUI.lua/SUI.lua.bak files.

Path: `World of Warcraft\_retail_\WTF\Account\AccountName\SavedVariables`

**Comment by GWEMLINN** [comment]
Hey thanks a lot!
