### ISSUE TITLE
Action Forbidden [BUG]

### ISSUE THREAD

**Issue by Mad-Monty** [Syiana/SUI#67]
**Describe the bug**
SUI stops functioning and does not allow the use of abilities on the action bar, chat window, or other UI elements.

**To Reproduce**
I dont have the exact way to reproduce this. It has been happening on every character ive played so far and has resulted in doing a /reload numerous times in the past few days.

**Expected behavior**
Expected SUI to allow the use of the UI.

**Screenshots**
Hard to show in picture.

**Which World of Warcraft version (please complete the following information):**
Retail Version 10.0.2.46924

**Additional context**
(BugGrabber - Action bar error)
1x [ADDON_ACTION_FORBIDDEN] AddOn 'SUI' tried to call the protected function 'UseAction()'.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `UseAction'
[string "@FrameXML/SecureTemplates.lua"]:364: in function `handler'
[string "@FrameXML/SecureTemplates.lua"]:690: in function <FrameXML/SecureTemplates.lua:672>
[string "@FrameXML/SecureTemplates.lua"]:704: in function <FrameXML/SecureTemplates.lua:697>
[string "@FrameXML/SecureTemplates.lua"]:746: in function `SecureActionButton_OnClick'
[string "@FrameXML/ActionButton.lua"]:109: in function `TryUseActionButton'
[string "@FrameXML/MultiActionBars.lua"]:14: in function <FrameXML/MultiActionBars.lua:8>
[string "=[C]"]: in function `MultiActionButtonDown'
[string "MULTIACTIONBAR2BUTTON11"]:2: in function <[string "MULTIACTIONBAR2BUTTON11"]:1>

(BugGrabber - Action bar error 2)
1x [ADDON_ACTION_BLOCKED] AddOn 'SUI' tried to call the protected function 'MultiBarBottomLeft:SetPointBase()'.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `SetPointBase'
[string "@FrameXML/EditModeSystemTemplates.lua"]:72: in function `SetPoint'
[string "@FrameXML/EditModeManager.lua"]:628: in function `UpdateBottomActionBarPositions'
[string "@FrameXML/EditModeManager.lua"]:554: in function `UpdateActionBarLayout'
[string "@FrameXML/EditModeSystemTemplates.lua"]:670: in function `UpdateGridLayout'
[string "@FrameXML/ActionBar.lua"]:350: in function `UpdateVisibility'
[string "@FrameXML/ActionBar.lua"]:317: in function `Hide'
[string "@FrameXML/PetActionBar.lua"]:182: in function `Update'
[string "@FrameXML/PetActionBar.lua"]:84: in function <FrameXML/PetActionBar.lua:70>
[string "=[C]"]: ?

(BugGrabber - Chat error)
1x [ADDON_ACTION_BLOCKED] AddOn 'SUI' tried to call the protected function 'ChatFrame1:Show()'.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `Show'
[string "@FrameXML/FloatingChatFrame.lua"]:2111: in function `FCFDock_UpdateTabs'
[string "@FrameXML/FloatingChatFrame.lua"]:2085: in function `FCFDock_SelectWindow'
[string "@FrameXML/FloatingChatFrame.lua"]:1599: in function `FCF_SelectDockFrame'
[string "@FrameXML/FloatingChatFrame.lua"]:1636: in function `FCF_Tab_OnClick'
[string "*FloatingChatFrame.xml:309_OnClick"]:1: in function <[string "*FloatingChatFrame.xml:309_OnClick"]:1>
[string "=[C]"]: ?

(BugGrabber - Targeting error)
3x [ADDON_ACTION_FORBIDDEN] AddOn 'SUI' tried to call the protected function 'TargetUnit()'.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `TargetUnit'
[string "@FrameXML/EditModeManager.lua"]:1519: in function `RefreshTargetAndFocus'
[string "@FrameXML/EditModeManager.lua"]:1463: in function `OnEditModeEnter'
[string "@FrameXML/EditModeManager.lua"]:170: in function `EnterEditMode'
[string "@FrameXML/EditModeManager.lua"]:192: in function <FrameXML/EditModeManager.lua:190>
[string "=[C]"]: ?
[string "=[C]"]: in function `Show'
[string "@FrameXML/UIParent.lua"]:2853: in function `SetUIPanel'
[string "@FrameXML/UIParent.lua"]:2657: in function `ShowUIPanel'
[string "@FrameXML/UIParent.lua"]:2561: in function <FrameXML/UIParent.lua:2557>
[string "=[C]"]: in function `SetAttribute'
[string "@FrameXML/UIParent.lua"]:3159: in function `ShowUIPanel'
[string "*GameMenuFrame.xml:94_OnClick"]:2: in function <[string "*GameMenuFrame.xml:94_OnClick"]:1>

**Comment by cpfowler** [comment]
I also got this bug for action bars:

2x [ADDON_ACTION_FORBIDDEN] AddOn 'SUI' tried to call the protected function 'UseAction()'.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `UseAction'
[string "@FrameXML/SecureTemplates.lua"]:364: in function `handler'
[string "@FrameXML/SecureTemplates.lua"]:690: in function <FrameXML/SecureTemplates.lua:672>
[string "@FrameXML/SecureTemplates.lua"]:704: in function <FrameXML/SecureTemplates.lua:697>
[string "@FrameXML/SecureTemplates.lua"]:746: in function `SecureActionButton_OnClick'
[string "@FrameXML/ActionButton.lua"]:109: in function `TryUseActionButton'
[string "@FrameXML/ActionButton.lua"]:144: in function `ActionButtonDown'
[string "ACTIONBUTTON2"]:2: in function <[string "ACTIONBUTTON2"]:1>

**Comment by muleyo** [comment]
This happens if you don't reload after changing keybinds or exiting the EditMode etc.

Please reload everytime you do UI/Interface changes, we can't fix this as it's being caused by the EditMode etc.
