### ISSUE TITLE
Addon not working /sui works and all is blanked.

### ISSUE THREAD

**Issue by snawb** [Syiana/SUI#68]
Hi , the addon exists and enabled but does not work ,tried to reinstall bunch of times ,download older versions, disabling all addons except SUI , repairing game ! nothing seems to work.
The /SUI command work but all the tabs are blank ! reset UI button doesn’t react
the only thing reacts is the saved button which reloads my UI but does nothing apart from that 
Retail dragonflight
Game version up to date
Addon version up to date.
Thanks in advance , ps love the addon:)

**Comment by muleyo** [comment]
You need to delete your SavedVariables SUI.lua/SUI.lua.bak files.

Path: `World of Warcraft\_retail_\WTF\Account\AccountName\SavedVariables`
