### ISSUE TITLE
[BUG] XP Bar missing

### ISSUE THREAD

**Issue by Master0fEvil** [Syiana/SUI#76]
**Describe the bug**
XP bar is missing when 'Actionbar' option is set to small

**To Reproduce**
1. Go to SUI settings menu
2. Click on 'Actionbar'
3. Under 'Actionbar' option select small
4. no XP bar :(

**Expected behavior**
A smaller scale XP bar to exist beneath the actionbars

**Which World of Warcraft version :**
 - Wotlk

Thank you for this awesome addon

**Comment by muleyo** [comment]
closed as Classic isnt supported anymore.
