### ISSUE TITLE
[BUG] sui showing empty menu

### ISSUE THREAD

**Issue by Hakwish** [Syiana/SUI#78]
**Describe the bug**
hi, when i type /Sui, it shows an empty menu in all tabs, and it is not making any effect on the game, i would hep if you can fix it, this is a must have addon for me, thank's for your work 

![Capture d’écran 2022-12-26 201951](https://user-images.githubusercontent.com/119515603/209577990-94303f4b-3bf2-45f0-a2be-f7298a91098d.jpg)

**Comment by criptodev** [comment]
Hi this is a temporary fix I just see, thanks to muleyo(a member of discord comunity):

Simply delete your SavedVariables "SUI.lua" file. if you have the Curse Client, you can delete all settings by right-clicking SUI.
then it should work just fine again

![image](https://user-images.githubusercontent.com/18405453/210171502-95405272-9728-47e5-bc21-e6201816f417.png)


This should work until a more permanent fix it's implemented.

**Comment by muleyo** [comment]
As @criptodev said, you'll need to reset your SavedVariables (through Curse Client) or go into the SavedVariables folder and delete the "SUI.lua" and "SUI.lua.bak" files.
