### ISSUE TITLE
Target of target frame

### ISSUE THREAD

**Issue by Rhythm093** [Syiana/SUI#79]
Not really a bug but is it possible to move the position of the target of target frame? 
*EDIT* same with the focus targets frame

![94caddbb59293ff6bfa6d4ea64a86938](https://user-images.githubusercontent.com/121497838/209670668-74f0586e-cf84-4c43-ae09-9721f26f0bd3.png)

**Comment by muleyo** [comment]
get MoveAny or a similar addon to move it.
