### ISSUE TITLE
[BUG/REQUEST] Character unit frame is not shown when in a rested area

### ISSUE THREAD

**Issue by Brikxy** [Syiana/SUI#80]
**Describe the bug**
When walking into a rested area (an inn) a resting indication icon shows up. With SUI enabled, the icon is not showing up.

**To Reproduce**
1. In WoW retail go to an inn 
2. Enter the inn
3. A rest icon does not popup to visualize you are in a resting area

**Expected behavior**
A rested icon/indicator is visible when entering a rested area. (It stops being showed when leaving the rested area)

**Screenshots**
SUI enabled:
![SUI enabled](https://user-images.githubusercontent.com/123244481/213868248-69b5fab0-4e5d-412a-b017-5b73b4c70536.png)

SUI Disabled:
![SUI disabled](https://user-images.githubusercontent.com/123244481/213868247-1109b151-9b3b-4432-a5c8-fc4250dd32b3.png)

**Which World of Warcraft version (please complete the following information):**
 - Retail

**Additional context**
When disabling the SUI addon the rest icon works as expected

**Comment by alexandrucancescu** [comment]
Same for me

**Comment by muleyo** [comment]
not a bug, it's intended.
