### ISSUE TITLE
welcome to SUI 

### ISSUE THREAD

**Issue by Randor92** [Syiana/SUI#81]
so i have been using SUI before but just returned after a long break and now when i start the game with updated addons etc its all just blacked out saying ''welcome to SUI'' and theres no way for me to turn it of without disabling the addon anyone got a fix?

![image](https://user-images.githubusercontent.com/123258571/213876316-1b617a83-5153-493a-84aa-59b43f8702c6.png)

**Comment by Nelaxyy** [comment]
Hey, I had the same issue. Just did a quick research and on Discord I read, that the WOTLK version won't be updated any longer, as the creator doesn't play Classic anymore. The statement from the creator is just 2 days old. Thought I share the news

**Comment by Xaero252** [comment]
And don't bother trying to help patch things up, they've been pretty aggressive against anyone who tries to help.

**Comment by muleyo** [comment]
SUI Classic won't be updated anymore as I don't play the game anymore. I'm sorry but you'll have to search for an alternative for classic.
