### ISSUE TITLE
Texture issue since 10.0.5 release [BUG]

### ISSUE THREAD

**Issue by Valyentx** [Syiana/SUI#84]
**Describe the bug**
I have been using SUI for about 2 weeks now and since the 10.0.5 patch dropped I have been having a texture issue where the dark outlines are not where they are supposed to be, especially on the action bars.

**To Reproduce**
Just enable the addon

**Expected behavior**
To work as it has been for the last 2 weeks of using.

**Which World of Warcraft version (please complete the following information):**
 - Retail

**Additional context**

![Capture](https://user-images.githubusercontent.com/123598321/214695487-d628bc3c-8984-4747-88cf-1c57d18d942d.PNG)

**Comment by whitesn4** [comment]
Experiencing the same issue.

**Comment by muleyo** [comment]
Fixed with latest update.
