### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by italoroad** [Syiana/SUI#85]
**Describe the bug**
Getting stuck at the "Welcome to SUI" screen

**To Reproduce**
Logging into the game with the addon on

**Expected behavior**
The normal behavior of the addon

**Screenshots**
![WoWScrnShot_012623_150437](https://user-images.githubusercontent.com/33289584/214914422-9af60188-5415-4006-984f-fb0c76553999.jpg)

**Which World of Warcraft version (please complete the following information):**
 - Wotlk

**Additional context**
Tried to click anywhere and press buttons on keyboard, typed /sui on the chat bar also, but nothing works

**Comment by muleyo** [comment]
WOTLK doesnt get updated anymore.
