### ISSUE TITLE
[BUG] Buff numbers are buggy

### ISSUE THREAD

**Issue by jfbigorna** [Syiana/SUI#86]
**Describe the bug**
The duration of the buffs is buggy after 10.0.5 update.

**Expected behavior**
The buff duration it's inside the icons and not at the bottom as it should be, in some moments it seems that there are two numbers on top of each other, not making the duration of the buffs clear. It's not a big deal, but it bothers me.

**Screenshots**
https://imgur.com/a/QxlCaJ6

**Which World of Warcraft version (please complete the following information):**
 - Retail

**Comment by muleyo** [comment]
Not an SUI issue. You are clearly using another addon for the numbers.

**Comment by jfbigorna** [comment]
no, I'm not using it.

https://youtu.be/l_PA08tmlB4
