### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Aikryo** [Syiana/SUI#87]
**Describe the bug**
Since a couple of Days, i don't see anymore by pressing escape the Button to come to the Setting-Menu? I can't set up the UI.

**To Reproduce**
1. press Escape inGame
2. dont see anymore a Button to come in the Setting Menu 

**Which World of Warcraft version (please complete the following information):**
 - Wotlk

**Additional context**
its would be nice to set up the ui^^

**Comment by muleyo** [comment]
Classic has been discontinued.
