### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Bennybultsax** [Syiana/SUI#88]
**Describe the bug**
On Wrath Classic the addon is partly working. Since Ulduar patch you can no longer /SUI to customize or find it when you press escape. Also the action bars are no longer tinted black. However, some functionality still exist like class coloring unit frames and auto repairing which I had set up previously when the addon was working. So it is still existing in the background. 

**Which World of Warcraft version (please complete the following information):**
 - Wotlk

**Comment by muleyo** [comment]
Classic has been discontinued.
