### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by jfbigorna** [Syiana/SUI#90]
**Describe the bug**
I decided to do a deeper test than simply posting that the numbers are "broken" (sorry about the last post), and I noticed that there are only a few.

I reset the game's interface (I deleted the WTF, Cache and Interface folders), I downloaded only the SUI.

The numbers for weapon enchants, foods (when you are eating, the numbers are normal, but the food buff is not), and flasks are "broken".

I tested the buffs during combat.
Everything working perfectly, except for the Sated caused by Bloodlust, the numbers end up "breaking" too.

I made a video to show everything I found, everything I tested.

I don't know if this has anything to do with it, but the game is in PT-BR, resolution is 2560x1080 

**Screenshots**

I made a video to show everything I found, everything I tested

it's easier watching the video than the screenshots.

https://youtu.be/g5Dzdm7V6OY

**Which World of Warcraft version (please complete the following information):**
 - Retail

**Additional context**
no addons, only SUI

without any additional fonts.

**Comment by muleyo** [comment]
Should be fixed with the latest update.
