### ISSUE TITLE
[BUG] /sui command doesn't work for WoTLK classic 3.4.1

### ISSUE THREAD

**Issue by 4egito** [Syiana/SUI#94]
Describe the bug
"/sui" command doesn't work

To Reproduce

Type "/sui" in the chat window
Press "Enter"
Nothing happens
Expected behavior
Command should opens the menu which contains all addon settings

Which World of Warcraft version (please complete the following information):
The problem started after the last update of WoTLK patch: 3.4.1
In version 3.4.0 everything was completely fine but now the command doesn't work.

Additional context
I don't remember all the functionalities and since i can't open the menu to check them can't even say what really works or not but for sure "auto selling junk" functionality doesn't work as well. Since the addon version is for 3.4.0 i assume it has to be updated...

![1](https://user-images.githubusercontent.com/52432938/219134016-5235bc87-6035-472c-b58f-67e4fd1b753f.png)
![2](https://user-images.githubusercontent.com/52432938/219134020-0a86cd2d-b45f-4eae-90e2-bb56dbed31d1.png)

**Comment by 4egito** [comment]
does that addon still have support? for 1 month at least give some response damn... Or i need to replace this one with proper addon?

**Comment by Megajuaco** [comment]
No support for WOTLK only for retail and ERA
