### ISSUE TITLE
[BUG] Can't get out of the "Welcome to SUI" overlay when installing the addon. Nothing responds. I can only move my character using the keyboard. /SUI doesnt work as reported earlier

### ISSUE THREAD

**Issue by prebenfj** [Syiana/SUI#95]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Which World of Warcraft version (please complete the following information):**
 - Retail
 - Wotlk
 - Tbc
 - Vanilla

**Additional context**

**Comment by prebenfj** [comment]
**Describe the bug**
There is no way known to me to exit the dark Overlay containing the welcome message after installing the addon. I am using a Macbook Pro 14.

**To Reproduce**
Steps to reproduce the behavior:

**Step 1:**
Install the addon freshly

**Step 2:**
Have Wotlk version 3.41

No error, just no response

**Expected behavior**
Expected to be able to remove the layer by exiting (esc) or a cross, or a button. 



**Game Version**
Wotlk

**Comment by Develinn** [comment]
I have the same problem

**Comment by Sparty07** [comment]
Hello.
Same issue here

**Comment by Lanacan** [comment]
Same issue

**Comment by Megajuaco** [comment]
Is not working on WOTLK only on Retail and ERA

**Comment by ninjaskija** [comment]
Same here...

**Comment by maQZ89** [comment]
Same here for Classic Era PTR. 
On Classic Era Live its working for me. 
Will there be a fix for Classic HC Launch? 
Would appreciate that a lot!

**Comment by itsDaiton** [comment]
Issue still remains on the official Classic Era HC servers as of their launch. Reproduced by downloading the addon.

**Comment by pwnlads** [comment]
Same happening to me on Classic hardcore - anyone found a way to fix this? - thank you

**Comment by muleyo** [comment]
we dont support classic anymore.

**Comment by Megajuaco** [comment]
I remember that you said the same last time, then it got updated and now here we are, are you gonna support or not??
