### ISSUE TITLE
No exp bar at "small actionbar"

### ISSUE THREAD

**Issue by Megajuaco** [Syiana/SUI#96]
**Describe the bug**

**To Reproduce**
1. Go to 'SUI options.'
2. Click on actionbar menu
3. Set Actionbar tu Smal and /reload
4. UI wont show exp bar

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/90938494/232250568-a33c7241-25c2-417d-8440-ed4fabcc45df.png)

**Which World of Warcraft version (please complete the following information):**

 - Vanilla

**Additional context**
If you change to default the exp bar will show.

**Comment by muleyo** [comment]
this is intended.
